conn:
  #server: '127.0.0.1:57314'
  server: 'frontend:57314'
  cert: ''
  timeout:
    dial: 5s
    file: 1m
throughput:
  concurrency: 8
  chunk: 32768
  delay: 0s
files:
  #patterns:
  #  - '/glob/to/your/files/*'
  patterns:
    - '/data/uploads/*'
  delete: true
  gatekeeper: true
response:
  log: '/var/log/strelka/strelka.log'
